workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Build iOS Simulator App
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE \
          -scheme $XCODE_SCHEME \
          -sdk iphonesimulator \
          -configuration Release \
          -destination "platform:iOS Simulator, id:4DB945BB-B366-4387-92E4-365597009B20, OS:18.2, name:iPhone 16" \
          -archivePath build/ios-simulator \
          clean archive
    artifacts:
      - build/ios-simulator.xcarchive/Products/Applications/Runner.app
