workflows:
  ios-simulator-workflow:
    name: iOS Simulator Build
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up flutter
        script: |
          flutter clean
          flutter pub get
          
      - name: Set up pods
        script: |
          cd ios
          pod install
          
      - name: Set up iOS simulator
        script: |
          xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-2
          
      - name: Build iOS Simulator App
        script: |
          xcodebuild clean archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            -archivePath build/ios-simulator
            
    artifacts:
      - build/ios-simulator/**/*.app
      - build/ios-simulator/**/*.dSYM