name: Flutter iOS Simulation Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build iOS simulator
      run: flutter build ios --simulator --debug
    
    - name: Upload iOS simulator build
      uses: actions/upload-artifact@v3
      with:
        name: ios-simulator-build
        path: build/ios/iphonesimulator
