name: Flutter iOS Simulator Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for iOS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Set up Flutter (using 3.7.0 or other stable version)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'   # You can try 'latest' or '3.7.0'
      
      - name: Build iOS Simulator
        run: flutter build ios --simulator --no-codesign
